# Generated by Django 4.1.5 on 2023-02-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0003_profile_birthday_profile_hometown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
